# Travis CI
language: ruby
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - gem install bundler
script : script/cibuild
sudo: false
notifications:
  email: false
branches:
  only:
    - master

rvm:
- 2.3.1
- 2.3.0
env:
  - ""
  - BUNTO_VERSION=3.2.1
  - BUNTO_VERSION=3.0.0
matrix:
  allow_failures:
    - # GitHub Pages
      rvm: 2.1.1
      env: GH_PAGES=true
  include:
    - # Ruby 2.2.5
      rvm: 2.2.5
      env: BUNTO_VERSION=3.0.0
